# Generated by Django 5.0.1 on 2024-01-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorpage',
            options={'verbose_name': 'Author Page', 'verbose_name_plural': 'Author Pages'},
        ),
    ]
